Fix build when windows.h is included
The build failed when  windows.h was included, for example
for Qt for Python:

Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x64
QtCoap/qcoapresource.h(57): error C2236: unexpected token 'struct'. Did you forget a ';'?
QtCoap/qcoapresource.h(57): error C2332: 'struct': missing tag name
QtCoap/qcoapresource.h(57): error C2059: syntax error: ')'

Undefine interface to fix this (similar to
qtbase/786d23bb4966b6697ac04c43158e2312d898e133).

Change-Id: Ie5660ece384935b1163f68ee74833d0cc6f95b4c
Reviewed-by: Maurice Kalinowski <maurice.kalinowski@qt.io>
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
(cherry picked from commit 60b8f37590660e8a26a417705420e07b1a529611)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>